[package]
name = "rcada_server"
version = "0.1.0"
edition = "2024"

[dependencies.rcada_core]
path = "../rcada_core"

[dependencies.dashmap]
version = "6.1"

[dependencies.chrono]
workspace = true
features = ["clock"]
