[package]
name = "rcada_modbus_simulator"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors.workspace = true

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
