[package]
name = "rcada_core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors.workspace = true

[dependencies.chrono]
workspace = true

[dependencies.smol_str]
workspace = true

[dependencies.serde]
workspace = true
